### ISSUE TITLE
Events scraping properly or improper markup?

### ISSUE THREAD

**Issue by chrisaldrich** [indieweb/this-week#3]
In today's (8/12/16) edition, the upcoming note about HWC for 8/24 includes most of the usual suspects, but leaves off Los Angeles, despite the fact that many of them are listed as TBD while LA actually has data.

Am I missing something that causes it to skip over LA, or is something else going on?

**Comment by gRegorLove** [comment]
@chrisaldrich This is pulled from https://indieweb.org/events, I believe. When you edit that you'll see the one-day-event template which has parameters for multiple locations. I think LA got left out by accident when I replicated some of those events.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/this-week/issues/3#issuecomment-239997151" class="u-in-reply-to"></a>Thanks @gRegorLove. Hopefully LA will be regularly recurring now, so hopefully it gets replicated properly going forward.
