### ISSUE TITLE
unclear attribution for externally submitted IndieNews posts

### ISSUE THREAD

**Issue by sknebel** [indieweb/this-week#6]
I submitted Zegnat's blogpost to IndieNews via a bookmark on my site. It now shows up in the newsletter with "by <my-bookmark-post-url>":
![grafik](https://user-images.githubusercontent.com/1082036/27793948-5a99c28c-6000-11e7-891f-bc73f242c855.png)

This reads like an author statement, which it isn't. Alternatives would be "submitted by" (and /authorship discovery on my post) or "via" or just leaving it off completely. Ideally, it would attempt to discover the author of the submitted post first, but we know this doesn't work in this case (due to XRay not being able to talk to the Martijns site, for unknown reasons), so there has to be a fallback

**Comment by aaronpk** [comment]
This was fixed on the IndieNews side: https://github.com/aaronpk/IndieNews/commit/345c51a14ee530da993647f2cfe144678b1246a2
