### ISSUE TITLE
Individual newsletters need webmention endpoint!

### ISSUE THREAD

**Issue by tantek** [indieweb/this-week#8]
Individual newsletters like https://indieweb.org/this-week/2017-11-03.html need webmention endpoint!

**Comment by jalcine** [comment]
What would that provide? The ability to amend / add notes to it?

**Comment by jalcine** [comment]
What would that provide? The ability to amend / add notes to it?

(Originally published at: https://v2.jacky.wtf/post/ababea36-dae4-4e5b-9c57-5c566c469417)

**Comment by sknebel** [comment]
This has been fixed last year in https://github.com/indieweb/this-week/commit/bd6f38f63b8c3127055f8725d7d5b458952d8ec6 by @aaronpk (but only for newly generated ones)
